Repository xcat2/xcat-extensions, pull requests merged in 2018-06, with the labels that each got.

#6 combine xcatha-setup and xcatha-failover into xcatha.py
  HA/README.rst
  HA/xcatha.py
  HA/xcatha_failover.py
  HA/xcatha_setup.py
Labels: HA

#7 Long hostname and makedns verification
  HA/xcatha.py
Labels: HA

#8 Implementing dryrun function
  HA/README.rst
  HA/xcatha.py
Labels: HA

#12 Dryrun and display enhancements
  HA/xcatha.py
Labels: HA

#16 Dryrun enhancements part 3
  HA/xcatha.py
Labels: HA

#19 Cleanup INFO and DEBUG messages
  HA/xcatha.py
Labels: HA

#27 Support interactive deactivate
  HA/xcatha.py
Labels: sprint1

#31 Remove DB question
  HA/xcatha.py
Labels: HA

#32 move the xcatha.py doc to README
  README.rst
Labels: HA, sprint2

#34 fix interactive mode do not need to cleanup env
  HA/xcatha.py
Labels: sprint2
